# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('Company_name', models.CharField(max_length=100, verbose_name='Company_name')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('phone', models.IntegerField()),
                ('Birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='blouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('bust', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('waist', models.FloatField()),
                ('neck', models.FloatField()),
                ('halflength', models.FloatField()),
                ('Quaterlength', models.FloatField()),
                ('hip', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('Rsleeve', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('neck', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('Rsleeve', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='caftan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('underburst', models.FloatField()),
                ('neck', models.FloatField()),
                ('pocketline', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('bust', models.FloatField()),
                ('Quaterlength', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('Rsleeve', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='address')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date_created')),
                ('collectiondate', models.DateField(verbose_name='collectiondate')),
            ],
        ),
        migrations.CreateModel(
            name='gown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('bust', models.FloatField()),
                ('underburst', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('waist', models.FloatField()),
                ('halflength', models.FloatField()),
                ('Quaterlength', models.FloatField()),
                ('hip', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('Rsleeve', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer')),
            ],
        ),
        migrations.CreateModel(
            name='navbar_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=100, verbose_name='link name')),
                ('link', models.CharField(max_length=100, verbose_name='link')),
                ('icon', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FloatField()),
                ('advance', models.FloatField()),
                ('balance', models.IntegerField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer')),
            ],
        ),
        migrations.CreateModel(
            name='shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('collar', models.FloatField()),
                ('neck', models.FloatField()),
                ('chest', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('back', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('Rsleeve', models.FloatField()),
                ('waist', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer')),
            ],
        ),
        migrations.CreateModel(
            name='skirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('halflength', models.FloatField()),
                ('waist', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer')),
            ],
        ),
        migrations.CreateModel(
            name='sokoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('halflength', models.FloatField()),
                ('bottom', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('Company_name', models.CharField(max_length=100, verbose_name='Company_name')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('phone', models.IntegerField()),
                ('Birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('neck', models.FloatField()),
                ('collar', models.FloatField()),
                ('halflength', models.FloatField()),
                ('burst', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('armhole', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('Rsleeve', models.FloatField()),
                ('waist', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer')),
            ],
        ),
        migrations.CreateModel(
            name='trouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('waist', models.FloatField()),
                ('tight', models.FloatField()),
                ('roundkneel', models.FloatField()),
                ('flap', models.FloatField()),
                ('hip', models.FloatField()),
                ('rSit', models.FloatField()),
                ('bottom', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer')),
            ],
        ),
        migrations.AddField(
            model_name='caftan',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer'),
        ),
        migrations.AddField(
            model_name='buba',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer'),
        ),
        migrations.AddField(
            model_name='blouse',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metailnook.customer'),
        ),
    ]
