# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metailnook', '0005_auto_20180729_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suit',
            name='length',
            field=models.FloatField(),
        ),
    ]
