# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metailnook', '0008_auto_20180802_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_profile',
            name='Company_name',
            field=models.CharField(max_length=100, verbose_name='Company_name'),
        ),
        migrations.AlterField(
            model_name='account_profile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
