# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metailnook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=100, verbose_name='link name')),
                ('link', models.CharField(max_length=100, verbose_name='link')),
            ],
        ),
    ]
