# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metailnook', '0002_navbar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_link',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
