# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metailnook', '0002_auto_20180712_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
