# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metailnook', '0004_auto_20180712_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Password')),
                ('position', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.IntegerField()),
                ('Birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date_created')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
